Feature/use redux
jaferIdrees/bookstore-react pull request #3
Opened 2022-08-16 21:03 UTC by jaferIdrees

### Project requirements

- First of all - make sure that you keep state immutable in reducers!
- Secondly, change the default state in your books reducer from an empty array to an array with a few books. One of the goals is to display them in your React components.
- Import Redux Provider and your store in the main component of your React app.
- Connect your app to the Redux store.
- Make sure that list of books displays books from Redux store.
- Use useSelector to consume the state.
- In your React component responsible for adding new books, add functionality for "Add new" button click:
- Import Redux useDispatch.
- Set the data inputs in the local React state (set title and author - NOTE: categories and comments are NOT part of this step).
- Takes the inputs from the state and generate a unique id and add them to an object.
- Once your new book object is ready to be submitted to Redux store, dispatch a corresponding action (import Action Creator that you created before and use it here).
- In your React component responsible for removing books, add a functionality for "Remove" button click:
- Import Redux useDispatch.
- Dispatch a corresponding action (import Action Creator that you created before and use it here).
- In your React component responsible for categories, add a functionality for "Check status" button click:
- Import Redux useDispatch.
- Dispatch a corresponding action (import Action Creator that you created before and use it here).

2022-08-16 22:09 UTC, FrederickMih requested changes
Hi @jaferIdrees , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


# To Highlights

- Github workflow has been followed :heavy_check_mark: 
- PR has a title and summary :heavy_check_mark: 
- No Linter issue detected :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-16 22:09 UTC, FrederickMih commented on src/components/AddBookForm.js
>  function AddBookForm() {
- [x] Hi @jaferIdrees, based on the requirements of this project, this component should contain a local state with title and author. They should have their inputs that update the local state every time they update(onChange). I think you have the option of using the useState Hook when creating functional components as in your case or we can use React ES6 classes which come with a constructor function to instantiate the initial requirements of the components

2022-08-16 22:09 UTC, FrederickMih commented on src/components/AddBookForm.js
> +  const handleSubmit = (e) => {
- [x] Fantastic job :+1: for implementing this function but let's keep in mind that based on the requirements of this project this function(handleSubmit) takes the inputs from the state and `generate a unique id` :red_circle:  and adds them to an object then dispatches the `addBook` action creator :+1: with the object as its argument. Therefore, kindly ensure that the unique id is generated as requested.

2022-08-16 22:09 UTC, FrederickMih commented on src/components/Categories.js
> +      <button type="button" onClick={() => dispatch(checkStatus())}>Check status</button>
- [ ] Based on the requirements of this project, this button should use a function `checkCategoriesStatus`(named as you wish) made in this component. The functions should dispatch the `checkStatus` action creator. Let's kindly implement this function inside this component.

2022-08-17 15:37 UTC, DammyShittu requested changes
Hi @jaferIdrees,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 15:37 UTC, DammyShittu commented on src/components/AddBookForm.js
> +      <input type="text" id="authorInput" required name="author" placeholder="Author" value={authorEntry} />
- [ ] You are yet to implement the use of local states for title and author as suggested. While it appears your inputs are defined by the bookData state, you seem to dispatch the input values directly which defeats the purpose of using the local state. You are expected to dispatch the state.

- [ ] You are also expected to set the value of the inputs using onChange

  If you are struggling with the local states and dispatch you can look at these articles where the onChange method is used properly
  -  [https://www.genui.com/resources/react-hooks-simplify](https://www.genui.com/resources/react-hooks-simplify)
  - [https://dmitripavlutin.com/controlled-inputs-using-react-hooks/](https://dmitripavlutin.com/controlled-inputs-using-react-hooks/)

2022-08-17 17:04 UTC, jaferIdrees commented on src/components/AddBookForm.js
> +      <input type="text" id="authorInput" required name="author" placeholder="Author" value={authorEntry} />
Hi @DammyShittu.
Many thanks for the advice 👍

2022-08-17 17:19 UTC, topeogunleye approved these changes
### Hi @jaferldrees, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title :heavy_check_mark:
 
## [Optional] suggestions:
* Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 17:45 UTC, closed without merging